Show progress on filesystem copy

diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -1,10 +1,32 @@
-#!/bin/sh
-
-. /usr/share/initramfs-tools/scripts/functions
+#!/bin/bash
 
 panic()
 {
 	printf "\n\n%s: %s\n\n" "Panic" "$@"
 	PS1="(build) " /bin/bash --norc
 	exit 1
+}
+
+log_begin_msg()
+{
+	echo "$@"
+}
+
+log_end_msg()
+{
+	echo "done"
+}
+
+run_scripts()
+{
+	rundir=${1}
+	[ -d ${rundir} ] || return
+	scripts=(${rundir}/*)
+	for script in "${scripts[@]}"; do
+		$script && ec=$? || ec=$?
+		if [ "$ec" -ne 0 ]; then
+			echo "E: $script failed with return $ec."
+			exit $ec
+		fi
+	done
 }
