This commit breaks it.

diff --git a/scripts/build/04squashfs b/scripts/build/04squashfs
--- a/scripts/build/04squashfs
+++ b/scripts/build/04squashfs
@@ -1,17 +1,17 @@
 #!/bin/bash
 
 DESC="Squashing root filesystem"
-ROOTFS=/tmp/rootfs
-OUTFILE=/tmp/iso/live/filesystem.squashfs
 
-source /tmp/scripts/functions
+source /scripts/functions
+
 log_begin_msg "${DESC}"
+[ -e ${ROOTFS_SQUASH_FILE} ] && log_end_msg "cached"
+echo ${ROOTFS_SQUASH_FILE
+exit 0
 
 {
   DIRS=(${ROOTFS}/*/)
   n=${#DIRS[*]}; i=0
-  outdir=$(dirname $OUTFILE)
-  [ -d $outdir ] || mkdir -p $outdir
   for dir in "${DIRS[@]}"; do
     PCT=$(( 100*(++i)/n ))
 cat <<EOF
@@ -20,9 +20,10 @@ $PCT
 Processing ${dir}...
 XXX
 EOF
-    mksquashfs ${dir} ${OUTFILE} >/dev/null 2>&1
+    mksquashfs ${dir} ${ROOTFS_SQUASH_FILE} #>/dev/null 2>&1
+    [ $? -ne 0 ] && abort "mksquashfs failed"
   done
 } | whiptail --title "${DESC}" \
   --gauge "Calculating..." 10 78 0
 
-log_end_msg
+log_end_msg "done"
diff --git a/scripts/functions b/scripts/functions
--- a/scripts/functions
+++ b/scripts/functions
@@ -1,10 +1,8 @@
 #!/bin/bash
 
-panic()
+abort()
 {
-	printf "\n\n%s: %s\n\n" "Panic" "$@"
-	PS1="(build) " /bin/bash --norc
-	exit 1
+	echo "aborted"; printf "\n\n%s: %s\n\n" "Reason" "$@"; exit 1
 }
 
 log_begin_msg()
@@ -14,7 +12,7 @@ log_begin_msg()
 
 log_end_msg()
 {
-	echo "done"
+	echo "${@}"; exit 0
 }
 
 run_scripts()
@@ -25,6 +23,7 @@ run_scripts()
 	for script in "${scripts[@]}"; do
 		$script && ec=$? || ec=$?
 		if [ "$ec" -ne 0 ]; then
+			PS1="(build) " /bin/bash --norc
 			echo "E: $script failed with return $ec."
 			exit $ec
 		fi
